# Generated by Django 2.0.4 on 2018-11-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectimage',
            new_name='projectimage1',
        ),
        migrations.AddField(
            model_name='project',
            name='projectimage2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='projectimage3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
