# Generated by Django 2.0.4 on 2018-11-05 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20181105_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='framework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='framework', to='projects.Framework'),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='language', to='projects.Language'),
        ),
    ]
