# Generated by Django 2.0.4 on 2018-12-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20181120_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Language')),
            ],
        ),
    ]
