# Generated by Django 2.2 on 2019-07-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
