# Generated by Django 2.2 on 2019-07-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_tech_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_tags',
        ),
    ]
