# Generated by Django 2.1.5 on 2019-03-10 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('job_role', models.CharField(choices=[('Full Stack Developer', 'Full Stack Developer'), ('Frontend Developer', 'Frontend Developer'), ('Backend  Developer', 'Backend  Developer'), ('Android  Developer', 'Android  Developer'), ('Graphic Designer', 'Graphic Designer'), ('IOS Developer', 'IOS Developer'), ('Data Scientist', 'Data Scientist')], default='Full Stack Developer', max_length=30)),
                ('dev_experience', models.CharField(choices=[('Entry', 'Entry'), ('Junior', 'Junior'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior')], default='Mid-Level', max_length=30)),
                ('engagement_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], default='Full-time', max_length=30)),
                ('tech_stack', models.CharField(max_length=500)),
                ('num_devs_wanted', models.IntegerField(default=1)),
                ('location', django_countries.fields.CountryField(max_length=2, null=True)),
                ('remuneration', models.CharField(help_text='in dollars ($)', max_length=45)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('position_filled', models.BooleanField(default=False)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devs', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='marketplace.Job')),
            ],
        ),
    ]
