# Generated by Django 2.2 on 2019-04-28 11:54

from django.db import migrations
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_devrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devrequest',
            name='dev',
        ),
        migrations.AddField(
            model_name='devrequest',
            name='developers',
            field=separatedvaluesfield.models.SeparatedValuesField(max_length=150, null=True),
        ),
    ]
