# Generated by Django 2.2 on 2019-07-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20190428_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='stage',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
