# Generated by Django 2.2 on 2019-07-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_jobapplication_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
