# Generated by Django 2.2 on 2019-07-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_job_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interviewdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notes',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
