# Generated by Django 2.2 on 2019-07-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20190717_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='interviewdate',
            new_name='interview',
        ),
    ]
