# Generated by Django 2.2 on 2019-07-22 18:07

from django.db import migrations
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_auto_20190717_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devrequest',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='devrequest',
            name='completed',
        ),
        migrations.AlterField(
            model_name='devrequest',
            name='paid',
            field=separatedvaluesfield.models.SeparatedValuesField(max_length=150, null=True),
        ),
    ]
