# Generated by Django 2.2 on 2019-07-23 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0010_auto_20190722_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devrequest',
            name='created',
        ),
        migrations.RemoveField(
            model_name='devrequest',
            name='developers',
        ),
        migrations.AddField(
            model_name='devrequest',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devaccount', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devrequest',
            name='interview',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devrequest',
            name='notes',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='devrequest',
            name='stage',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='devrequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
