# Generated by Django 2.2 on 2019-07-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_auto_20190726_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='devrequest',
            name='test',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='test',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
