# Generated by Django 2.2 on 2019-07-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_tech_tags'),
        ('marketplace', '0014_auto_20190729_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='devrequest',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
