# Generated by Django 2.2 on 2019-07-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_auto_20190729_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devrequest',
            old_name='test',
            new_name='test_stage',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='test',
            new_name='test_stage',
        ),
    ]
