# Generated by Django 2.2 on 2019-07-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_auto_20190729_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='devrequest',
            name='projectname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='projectname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
