# Generated by Django 2.2 on 2019-07-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_auto_20190729_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='devrequest',
            name='report',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='report',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
