# Generated by Django 2.2 on 2019-07-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_auto_20190729_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devrequest',
            old_name='projectname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='projectname',
            new_name='name',
        ),
    ]
