# Generated by Django 2.2 on 2019-07-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_auto_20190730_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='devrequest',
            name='interviewstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interviewstatus',
            field=models.BooleanField(default=False),
        ),
    ]
