# Generated by Django 2.2 on 2019-07-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_auto_20190730_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devrequest',
            name='interviewstatus',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='interviewstatus',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
