# Generated by Django 2.2 on 2019-08-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_auto_20190802_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='devrequest',
            name='candidatename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='candidatename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
