# Generated by Django 2.0.4 on 2018-12-18 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('recruiter', 'RECRUITER'), ('developer', 'DEVELOPER')], max_length=30, null=True)),
                ('stage', models.CharField(choices=[('profile_type_selection', 'profile_type_selection'), ('recuiter_filling_details', 'recuiter_filling_details'), ('developer_filling_details', 'developer_filling_details'), ('complete', 'complete')], default='profile_type_selection', max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('linkedin_url', models.CharField(max_length=500, null=True)),
                ('portfolio', models.CharField(blank=True, max_length=500, null=True)),
                ('github_repo', models.CharField(max_length=500, null=True)),
                ('language', models.CharField(blank=True, max_length=140, null=True)),
                ('framework', models.CharField(blank=True, max_length=140, null=True)),
                ('years', models.CharField(choices=[('1-2', '1-2'), ('2-4', '2-4'), ('4-above', '4-above')], max_length=30, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('availabilty', models.CharField(choices=[('fulltime', 'fulltime'), ('contract', 'contract'), ('remote', 'remote'), ('freelance', 'freelance')], max_length=30, null=True)),
                ('company', models.CharField(blank=True, max_length=140, null=True)),
                ('job_role', models.CharField(blank=True, max_length=140, null=True)),
                ('industry', models.CharField(blank=True, max_length=80, null=True)),
                ('staff_size', models.IntegerField(blank=True, null=True)),
                ('company_url', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
