# Generated by Django 2.0.4 on 2018-12-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='staff_size',
        ),
    ]
