# Generated by Django 2.0.4 on 2018-11-06 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='frameworks',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='programming_languages',
        ),
        migrations.AddField(
            model_name='profile',
            name='framework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='frameworks', to='projects.Framework'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='languages', to='projects.Language'),
        ),
    ]
