# Generated by Django 2.0.4 on 2018-11-19 15:50

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181119_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='core',
            field=models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('fullstack', 'fullstack'), ('android', 'android'), ('IOS', 'IOS'), ('devops', 'devops'), ('graphic design', 'graphic design')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
