# Generated by Django 2.0.4 on 2018-11-05 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20181105_2214'),
        ('accounts', '0002_auto_20181105_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='frameworks',
            new_name='framework',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='programming_languages',
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='languages', to='projects.Language'),
        ),
    ]
