# Generated by Django 2.0.4 on 2018-11-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181105_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
    ]
