# Generated by Django 2.0.4 on 2018-11-05 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20181105_2214'),
        ('accounts', '0004_auto_20181105_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='framework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='frameworks', to='projects.Framework'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='languages', to='projects.Language'),
        ),
    ]
