# Generated by Django 2.0.4 on 2018-11-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181119_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availabilty',
            field=models.CharField(choices=[('fulltime', 'fulltime'), ('contract', 'contract'), ('remote', 'remote'), ('freelance', 'freelance')], max_length=30, null=True),
        ),
    ]
