# Generated by Django 2.2 on 2019-05-16 09:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190508_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file',
            field=cloudinary.models.CloudinaryField(default=False, max_length=255),
        ),
    ]
