# Generated by Django 2.2 on 2019-05-16 18:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
