# Generated by Django 2.0.4 on 2018-12-03 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181128_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='framework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='frameworks', to='projects.Framework'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='languages', to='projects.Language'),
        ),
    ]
