# Generated by Django 2.2 on 2019-05-16 18:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190516_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=cloudinary.models.CloudinaryField(default=False, max_length=255),
        ),
    ]
