# Generated by Django 2.0.4 on 2018-12-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181203_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github_repo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
