# Generated by Django 2.0.4 on 2018-12-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181203_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github_repo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
