# Generated by Django 2.2 on 2019-05-16 18:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190516_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
