# Generated by Django 2.2 on 2019-07-02 10:10

from django.db import migrations
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190516_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language_tags',
            field=separatedvaluesfield.models.SeparatedValuesField(max_length=900, null=True),
        ),
    ]
