# Generated by Django 2.2 on 2019-07-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_language_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='language_tags',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
