# Generated by Django 2.2 on 2019-07-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190702_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified_skills',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
