# Generated by Django 2.2 on 2019-05-20 11:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190520_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blogsplashimage',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
