# Generated by Django 2.2 on 2019-05-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190520_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blogsplashimage',
            field=models.CharField(max_length=250),
        ),
    ]
