# Generated by Django 2.2 on 2019-05-20 14:15

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190520_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=martor.models.MartorField(),
        ),
    ]
