# Generated by Django 2.0.4 on 2018-10-07 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('stage', models.CharField(choices=[('project_selection', 'project_selection'), ('upload_candidate', 'upload_candidate'), ('payment_stage', 'payment_stage'), ('payment_verified', 'payment_verified'), ('send_credentials', 'send_credentials'), ('complete', 'complete')], default='project_selection', max_length=100)),
                ('completed', models.DateTimeField(auto_now=True, null=True)),
                ('project', models.ForeignKey(on_delete=False, to='projects.Project')),
                ('user', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='transaction',
            field=models.ForeignKey(on_delete=False, to='transactions.Transaction'),
        ),
    ]
