# Generated by Django 2.0.4 on 2018-10-08 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='names',
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(default='No Name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stage',
            field=models.CharField(choices=[('upload_candidate', 'upload_candidate'), ('payment_stage', 'payment_stage'), ('payment_verified', 'payment_verified'), ('send_credentials', 'send_credentials'), ('complete', 'complete')], default='upload_candidate', max_length=100),
        ),
    ]
