# Generated by Django 2.1.5 on 2019-01-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_applications_opencall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='opencall',
            name='deadline',
        ),
        migrations.AddField(
            model_name='transaction',
            name='deadline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
