# Generated by Django 2.1.5 on 2019-01-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20190124_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='deadline',
        ),
    ]
