# Generated by Django 2.0.4 on 2019-01-09 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
            preserve_default=False,
        ),
    ]
