# Generated by Django 2.0.4 on 2018-10-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='completed',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stage',
            field=models.CharField(choices=[('created', 'created'), ('upload_candidate', 'upload_candidate'), ('payment_stage', 'payment_stage'), ('payment_verified', 'payment_verified'), ('complete', 'complete')], default='upload_candidate', max_length=100),
        ),
    ]
