# Generated by Django 2.0.4 on 2018-10-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20181022_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
