# Generated by Django 2.0.4 on 2018-10-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stage',
            field=models.CharField(choices=[('created', 'created'), ('upload-candidates', 'upload-candidates'), ('payment-stage', 'payment-stage'), ('make-payment', 'make-payment'), ('payment-confirmed', 'payment-confirmed'), ('payment-verified', 'payment-verified'), ('complete', 'complete')], default='created', max_length=100),
        ),
    ]
