# Generated by Django 2.1.5 on 2019-01-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transaction_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='opencall',
        ),
    ]
