# Generated by Django 2.0.4 on 2018-10-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20181009_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='completed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
