# Generated by Django 2.1.5 on 2019-02-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_applications_opencall'),
    ]

    operations = [
        migrations.AddField(
            model_name='opencall',
            name='Projecttitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
