# Generated by Django 2.0.4 on 2019-01-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20190109_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='opencall',
            name='stage',
            field=models.CharField(default='payment', max_length=100),
        ),
    ]
