# Generated by Django 2.1.5 on 2019-02-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_opencall_projecttitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opencall',
            old_name='Projecttitle',
            new_name='projecttitle',
        ),
    ]
