# Generated by Django 2.0.4 on 2019-01-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_opencall_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opencall',
            name='stage',
            field=models.CharField(default='choice', max_length=100),
        ),
    ]
