# Generated by Django 2.0.4 on 2018-10-09 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20181009_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
        ),
    ]
