# Generated by Django 2.0.4 on 2019-01-10 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20190110_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='opencall',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
            preserve_default=False,
        ),
    ]
