# Generated by Django 2.0.4 on 2018-10-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20181009_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stage',
            field=models.CharField(choices=[('created', 'created'), ('upload-candidate', 'upload-candidate'), ('payment-stage', 'payment-stage'), ('payment-verified', 'payment-verified'), ('complete', 'complete')], default='upload_candidate', max_length=100),
        ),
    ]
