# Generated by Django 2.0.4 on 2019-01-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_opencall_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='stage',
        ),
    ]
