# Generated by Django 2.1.5 on 2019-04-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
