# Generated by Django 2.0.4 on 2019-01-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20190110_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='score',
            field=models.IntegerField(default=20, max_length=255),
            preserve_default=False,
        ),
    ]
