# Generated by Django 2.0.4 on 2018-10-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20181010_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
    ]
