# Generated by Django 2.0.4 on 2019-01-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_applications_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='score',
            field=models.IntegerField(),
        ),
    ]
