# Generated by Django 2.0.4 on 2018-10-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_remove_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
