# Generated by Django 2.0.4 on 2018-12-18 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidatesprojects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(default='awaiting candidate', max_length=100)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='devs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, null=True)),
                ('language', models.CharField(max_length=500, null=True)),
                ('framework', models.CharField(max_length=500, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('lastname', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='recruiters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('lastname', models.CharField(max_length=30, null=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('companyurl', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
