# Generated by Django 2.0.4 on 2018-11-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidatesprojects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField()),
                ('transaction', models.IntegerField()),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
