# Generated by Django 2.0.4 on 2018-12-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devs',
            name='github',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='devs',
            name='linkedin',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='devs',
            name='portfolio',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
