# Generated by Django 2.0.4 on 2019-01-14 11:02

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devs',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
