# Generated by Django 2.0.4 on 2018-12-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_devs_recruiters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devs',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recruiters',
            name='user',
        ),
    ]
