# Generated by Django 2.0.4 on 2018-11-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_candidatesprojects_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatesprojects',
            name='accepted',
        ),
        migrations.AddField(
            model_name='candidatesprojects',
            name='stage',
            field=models.CharField(choices=[('awaiting-candidate', 'awaiting-candidate'), ('invite-accepted', 'invite-accepted'), ('project-in-progress', 'project-in-progress'), ('project-completed', 'project-completed')], default='awaiting-candidate', max_length=100),
        ),
    ]
