# Generated by Django 2.0.4 on 2018-11-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20181123_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesprojects',
            name='stage',
            field=models.CharField(max_length=100),
        ),
    ]
