# Generated by Django 2.0.4 on 2018-12-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20181218_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devs',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='devs',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devs',
            name='firstname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='devs',
            name='framework',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='devs',
            name='language',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='devs',
            name='lastname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='companyurl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='firstname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='lastname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
