# Generated by Django 2.0.4 on 2018-11-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20181123_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesprojects',
            name='stage',
            field=models.CharField(default='awaiting candidate', max_length=100),
        ),
    ]
