# Generated by Django 2.0.4 on 2018-11-23 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20181123_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesprojects',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Framework'),
        ),
    ]
