# Generated by Django 2.0.4 on 2018-11-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20181123_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatesprojects',
            name='project',
        ),
    ]
