# Generated by Django 2.0.4 on 2018-11-24 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_remove_candidatesprojects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesprojects',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
