# Generated by Django 2.1.5 on 2019-02-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
