# Generated by Django 2.1.5 on 2019-04-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20190226_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.AddField(
            model_name='github',
            name='about',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
