# Generated by Django 2.1.5 on 2019-04-16 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0010_transaction_deadline'),
        ('frontend', '0011_auto_20190410_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', separatedvaluesfield.models.SeparatedValuesField(max_length=150, null=True)),
                ('keycompitency', separatedvaluesfield.models.SeparatedValuesField(max_length=150, null=True)),
                ('grading', separatedvaluesfield.models.SeparatedValuesField(max_length=150, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction')),
            ],
        ),
    ]
