# Generated by Django 2.1.5 on 2019-04-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_report_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='github',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
