# Generated by Django 2.2 on 2019-04-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_report_github'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Github',
        ),
    ]
