# Generated by Django 2.2 on 2019-05-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_delete_github'),
    ]

    operations = [
        migrations.DeleteModel(
            name='devs',
        ),
        migrations.DeleteModel(
            name='recruiters',
        ),
    ]
