# Generated by Django 2.2 on 2019-07-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_experience_tech_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='tech_tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
