# Generated by Django 2.2 on 2019-07-29 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_tech_tags'),
        ('marketplace', '0013_auto_20190726_1132'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0018_portfolio_tech_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesprojects',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectjob', to='marketplace.Job'),
        ),
        migrations.AddField(
            model_name='candidatesprojects',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='candidatesprojects',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiterproject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidatesprojects',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidatesprojects',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
        ),
    ]
