# Generated by Django 2.2 on 2019-07-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_auto_20190729_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatesprojects',
            name='job',
        ),
        migrations.RemoveField(
            model_name='candidatesprojects',
            name='project',
        ),
        migrations.RemoveField(
            model_name='candidatesprojects',
            name='recruiter',
        ),
    ]
