# Generated by Django 2.0.1 on 2018-01-18 18:07

from django.db import migrations


def create_subjects(apps, schema_editor):
    Subject = apps.get_model('classroom', 'Subject')
    Subject.objects.create(name='React js')
    Subject.objects.create(name='Express js')
    Subject.objects.create(name='Laravel')
    Subject.objects.create(name='Django')
    Subject.objects.create(name='Angular')
    Subject.objects.create(name='Angularjs')
    Subject.objects.create(name='Rubyonrails')
    Subject.objects.create(name='Nodejs')
    Subject.objects.create(name='Vue')
    Subject.objects.create(name='Javascript')
    Subject.objects.create(name='Python')
    Subject.objects.create(name='Java')
    Subject.objects.create(name='Sql')
    Subject.objects.create(name='C++')
    Subject.objects.create(name='C#')
    Subject.objects.create(name='Php')
    Subject.objects.create(name='Ruby')
    Subject.objects.create(name='Android')


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_subjects),
    ]