# Generated by Django 2.0.4 on 2018-12-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
