# Generated by Django 2.0.4 on 2018-12-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20181214_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
