# Generated by Django 2.1.5 on 2019-02-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_question_codesample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takenquiz',
            name='score',
            field=models.IntegerField(),
        ),
    ]
