# Generated by Django 2.1.5 on 2019-03-15 10:17

from django.db import migrations, models
import django.db.models.deletion
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20190225_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', separatedvaluesfield.models.SeparatedValuesField(max_length=150, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempquiz', to='classroom.Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempanswers', to='classroom.Student')),
            ],
        ),
    ]
