# Generated by Django 2.2 on 2019-06-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_auto_20190606_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.IntegerField(blank=True),
        ),
    ]
