# Generated by Django 2.0.4 on 2018-12-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_auto_20181206_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='color',
        ),
    ]
