# Generated by Django 2.0.4 on 2018-12-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_auto_20181207_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='quiz',
        ),
    ]
