# Generated by Django 2.0.4 on 2018-12-10 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0027_auto_20181210_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.Quiz'),
            preserve_default=False,
        ),
    ]
